name: Pull Request @ Main (CI/CD)

on:
  pull_request:
    branches:
      - main
    paths:
      - "backend/**"
      - "frontend/**"
      - "seeder/**"
      - ".github/workflows/pull-request-main.yml"
      - "docker-compose.integration.yml"

jobs:

  # e2e-tests:

  integration-tests:
    # needs: e2e-tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build & start containers
        run: docker-compose -f docker-compose.integration.yml up -d --build

      - name: Install frontend deps
        run: docker-compose -f docker-compose.integration.yml exec -T frontend sh -c "npm ci"

      - name: Run integration tests
        run: docker-compose -f docker-compose.integration.yml exec -T frontend sh -c "npm run test:integration"

      - name: Show app logs
        if: failure()
        run: docker-compose -f docker-compose.integration.yml logs frontend

      - name: Show backend logs
        if: failure()
        run: docker-compose -f docker-compose.integration.yml logs backend

      - name: Tear down containers
        run: docker-compose -f docker-compose.integration.yml down
